---
- name: Install dnsmasq
  ansible.builtin.apt:
    name:
      - dnsmasq
    state: present
    update_cache: true

- name: Replace dnsmasq.conf
  ansible.builtin.copy:
    src: 'etc/dnsmasq.conf'
    dest: '/etc/dnsmasq.conf'
    force: true
    mode: '644'
    owner: 'root'
  notify:
    - Restart dnsmasq
